logging:
  path: C:\Users\windows10\Desktop\LeTutor\logs

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/letutor
    username: root
    password: Mantu
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  h2:
    console:
      enabled: true
#    data:
#     mongodb:
#     uri: mongodb+srv://libas:123kaka@cluster-letutor.p3vng.mongodb.net/letutor?retryWrites=true&w=majority